version: '3'

services:
  
  app:
    image: fastapi
    ports:
      - 8000:8000
    # bind mounting the project dir to the container "app" with read-only previliges
    volumes:
      - ./:/usr/src/app:ro
    # env_file:
    #   - ./.env
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=fastapi
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - database

  database:
    image: postgres
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_vol:/var/lib/postgres/data

volumes:
  postgres_vol: